export const productos = [
    {
        id:1,
        nombre:"Vasija",
        precio:400,
        img:"../img/R.jpeg"
    },
    {
        id:2,
        nombre:"Cámara",
        precio:900,
        img:"../img/camara.jpg"
    },
    {
        id:3,
        nombre:"Radio",
        precio:500,
        img:"../img/radio.jpg"
    },
    {
        id:4,
        nombre:"Maquina de Tejer",
        precio:1000,
        img:"../img/maquinaDeTejer.jpg"
    },
    {
        id:5,
        nombre:"Teléfono",
        precio:400,
        img:"../img/telefono.jpg"
    },
    {
        id:6,
        nombre:"Relojes",
        precio:300,
        img:"../img/OIP.jpeg"
    },
    {
        id:7,
        nombre:"Bicicleta",
        precio:3000,
        img:"../img/bicicleta.jpg"
    },
    {
        id:8,
        nombre:"Tetera",
        precio:700,
        img:"../img/tetera.webp"
    },
    {
        id:9,
        nombre:"Mechero",
        precio:300,
        img:"../img/mechero.jpg"
    }
]